//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Detalle
    {
        [ScaffoldColumn(false)]
        public int idDetalle { get; set; }

        [Display(Name = "Producto")]
        public int idProducto { get; set; }

        [Display(Name = "Lista")]
        public int idLista { get; set; }
    
        public virtual Lista Lista { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
