//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle = new HashSet<Detalle>();
        }

        [ScaffoldColumn(false)]
        public int idProducto { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(55)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "El precio es requerido")]
        [Display(Name = "Precio")]
        public decimal precio { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La categoría es requerida"), MaxLength(55)]
        [Display(Name = "Categoría")]
        public string categoria { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }

        [DataType(DataType.Duration)]
        [Required(ErrorMessage = "El stock es requerido")]
        [Display(Name = "Stock")]
        public int stock { get; set; }

        
        [Display(Name = "Disponibilidad")]
        public bool disponibilidad { get; set; }


        [Display(Name = "Imágen")]
        public string imagen { get; set; }

        [Display(Name = "Negocio")]
        public int idNegocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
        public virtual Negocio Negocio { get; set; }
    }
}
