//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comerciante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comerciante()
        {
            this.Negocio = new HashSet<Negocio>();
        }

        [ScaffoldColumn(false)]
        public int idComerciante { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La base legal es requerida."), MaxLength(55)]
        [Display(Name = "Base Legal")]
        public string baseLegal { get; set; }

      
        [Display(Name = "Comerciante")]
        public int idPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio> Negocio { get; set; }
    }
}
