//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido
    {
        [ScaffoldColumn(false)]
        public int idPedido { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Fecha del pedido")]
        public System.DateTime fecha { get; set; }


        [Display(Name = "Comprobante")]
        public byte[] documento { get; set; }

        
        [Display(Name = "Cliente")]
        public int idCliente { get; set; }

        
        [Display(Name = "Lista")]
        public int idLista { get; set; }

        
        [Display(Name = "Forma de pago")]
        public int idFormaPago { get; set; }
    
        public virtual Forma_de_Pago Forma_de_Pago { get; set; }
        public virtual Lista Lista { get; set; }
    }
}
