//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public string categoria { get; set; }
        public string descripcion { get; set; }
        public int stock { get; set; }
        public bool disponibilidad { get; set; }
        public string imagen { get; set; }
        public int idNegocio { get; set; }
    
        public virtual Negocio Negocio { get; set; }
    }
}
